apiVersion: v1 
kind: Pod
metadata:
  name: node-select
  labels:
    project: roboshop
    env: dev
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "150m"
          memory: "200Mi"

  nodeSelector:
    purpose: selector
    

#kubectl label node <nodename> env=production
#kubectl get nodes --show-labels