apiVersion: v1 
kind: Pod
metadata:
  name: node-tolerate
  labels:
    project: roboshop
    env: dev
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "150m"
          memory: "200Mi"

  tolerations:
    - key: "graph"
      operator: "Equal"
      value: "node"
      effect: "NoSchedule"
  nodeSelector:
    purpose: selector


    #kubectl taint node <nodename> <key>=<value>:<effect>
    #kubectl taint node ip-192-168-55-199.ec2.internal graph=node:NoSchedule
