apiVersion: v1 
kind: Pod
metadata:
  name: node-tolerate
  labels:
    project: roboshop
    env: dev
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
        requests:
          cpu: "100m"
          memory: "128mi"
        limits:
          cpu: "150m"
          memory: "200mi"

  tolerations:
    - key:
      operator:
      value:
      effect:

  nodeSelector:
    purpose: selector