apiVersion: v1
kind: Pod
metadata:
  name: pod-affin

spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: instance
            operator: In
            values:
            - node1
      
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
          - key: instance
            operator: In
            values:
            - node2
  
  containers:
   - name: nginx
     image: nginx
     resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "150m"
          memory: "200Mi"